### ISSUE TITLE
Individual emoji UI items

### ISSUE THREAD

**Issue by OleAndreasER** [ITP2-G15/OpenEmojiPlatform#10]
![image](https://github.com/ITP2-G15/OpenEmojiPlatform/assets/89947900/ecf916d1-a494-4a03-afd7-22200fb0e54d)
![image](https://github.com/ITP2-G15/OpenEmojiPlatform/assets/89947900/3721b00d-a5c9-4b22-a6f2-ec4aaf6307d6)
Create reusable emoji icon "component" (fragment?) that will later be clickable.

**Comment by Steffenriv** [comment]
Branch did not auto close this issue, it is already merged. So i am closing it.
