### ISSUE TITLE
Create a json file including level data

### ISSUE THREAD

**Issue by Steffenriv** [ITP2-G15/OpenEmojiPlatform#106]
Set up a level object, and create some json data for this that includes 4 alternative choices and 1 correct choice that is the winner.

**Comment by michaelbrusegard** [comment]
```json
[
   {
      "emojiQuestion": "🇺🇲🇺🇲🇺🇲",
      "alternatives": [ "Norway", "Canada", "USA", "Cute dog" ],
      "correctAlternative": 2
   }
]
```

This is an example of how the data can look. Use the index of the item for the level number

**Comment by Andreasli02** [comment]
Done
