### ISSUE TITLE
Create emoji mock data

### ISSUE THREAD

**Issue by michaelbrusegard** [ITP2-G15/OpenEmojiPlatform#4]
Add a JSON file with mock data for different emojis that we can use to emulate the API. We copy data from the [Emojipedia website](https://emojipedia.org/). The data must be on this form:
```kotlin
val data = [{
  id: "grinning-face",
  title: "Grinning Face",
  category: "Smileys",
  subCategory: "Smiling & Affectionate",
  description: "A yellow face with simple..."
}]
```

**Comment by Andreasli02** [comment]
Issue done, but did not disappear. Closed manually.
