### ISSUE TITLE
Grid layout with categories for emojis

### ISSUE THREAD

**Issue by michaelbrusegard** [ITP2-G15/OpenEmojiPlatform#5]
Create a grid layout looking like the photo below including categories. It should be scrollable and responsive for different phone sizes.
![Screenshot 2024-02-06 at 12 53 17](https://github.com/ITP2-G15/Open-Emojiplatform/assets/56915010/53839c4b-b0de-4a43-8409-0275c3045362)

**Comment by Steffenriv** [comment]
Done just did not get closed for some reason.
