### ISSUE TITLE
Category buttons displaying sub-categories

### ISSUE THREAD

**Issue by michaelbrusegard** [ITP2-G15/OpenEmojiPlatform#8]
Category buttons that display the sub-categories in the same manner as the emoji overview. Here all emojis per category should be shown. The categories should be scrollable since there will be more categories than there is space for.
![Screenshot 2024-02-06 at 13 28 24](https://github.com/ITP2-G15/Open-Emojiplatform/assets/56915010/76413338-e98d-442c-acb4-1e69957f69c1)

**Comment by Steffenriv** [comment]
Issue merged with dev! Did not close issue on it's own, so closing manually.
